name: CI
os: windows
language: node_js
node_js:
  - 14

cache:
    directories:
        - node_modules

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

before_script:
  - echo "##[add-matcher]tsc.json"

script:
  - npm run lint
  - npm run test
