os: windows
language: node_js
node_js:
  - lts
install:
  - npm install
cache:
    directories:
        - node_modules

jobs:
  include:
    - stage: lint
      script:
        - node --version
        - npm --version
        - echo "Linting started ..."
        - npm run lint
    - stage: test
      script:
        - echo "Testing started ..."
        - npm test
        - echo "Testing finished."
      after_success:
          - npm run coverage
    - stage: npm release
      if: tag =~ ^v\d+\.\d+\.\d+$
      script:
        - echo "npm build started ..."
        - npm run build
        - echo "npm build finished."
        - echo "https://registry.npmjs.org/:_authToken=$NPM_DEPLOYMENT_KEY" > .npmrc
        - npm publish
