name: CI
os: windows
language: node_js
node_js:
  - 14

cache:
    directories:
        - node_modules

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

steps:
  - name: Clean install
    run: npm ci

  # Re: https://github.com/actions/setup-node/pull/125
  - name: Register Problem Matcher for TSC
    run: echo "##[add-matcher]tsc.json"

  - name: Tests
    run:  npm test -- --no-lint

  - name: Linter
    run:  npm run lint