os: windows
language: node_js
node_js:
  - lts

cache:
    directories:
        - node_modules

jobs:
  include:
    - stage: Lint and test
      script:
        - npm run lint
        - npm run test
    - stage: npm release
      script: npm run build
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_DEPLOYMENT_KEY'
        skip_cleanup: true
        edge: true
        on:
          tags: true