name: CI
os: windows
language: node_js
node_js:
  - 14

cache:
    directories:
        - node_modules

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  include:
    - stage: "Clean install"
      run: npm ci
    # Re: https://github.com/actions/setup-node/pull/125
    - stage: Register problem Matcher for TSC
      run: echo "##[add-matcher]tsc.json"
    - stage: Linter
      run: npm run lint
    - stage: Tests
      run: npm test