os: windows
language: node_js
node_js:
  - lts

cache:
    directories:
        - node_modules

script:
  - npm run lint
  - npm run test
  - echo "//registry.npmjs.org/:_authToken=\${NPM_DEPLOYMENT_KEY}" > .npmrc

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_DEPLOYMENT_KEY'
  edge: true # opt in to dpl v2
  skip_cleanup: true
  on:
    tags: true