os: windows
language: node_js
node_js:
  - 14

cache:
    directories:
        - node_modules

script:
  - npm run lint
  - npm run test

after_success:
  - npm publish

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_DEPLOYMENT_KEY'
  edge: true # opt in to dpl v2
  on:
    tags: true